### ISSUE TITLE
Alle EPs abgrasen und Änderungen loggen (User, Zeitstempel, etc.)

### ISSUE THREAD

**Issue by alxndr-w** [eaCe/activity_log#1]
Wäre das das Konzept dieses Addons? Mehr im Backend oder für Frontend-Aktivitäten?

**Comment by eaCe** [comment]
Für meine Zwcke eigentlich nur im Backend. User X hat Slice Y editiert usw.
Funktioniert natürlich auch im FE. Aber es ist nicht vorgesehen Klicks oder User-Interaktionen zu tracken.

**Comment by alxndr-w** [comment]
Filter: https://tofsjonas.github.io/sortable/

Das ist mein Favorit, kommt auch mit großen Tabellendatenmengen zurecht und kann die ggf. dynamisch nachladen.

**Comment by eaCe** [comment]
Ok, ich dachte nur an einen einfachen Filter für die Typen, das Datum kann man via REX-List sortieren.
Aber das werde ich mal mit aufnehmen.

**Comment by eaCe** [comment]
Also alle EPs werde ich da nicht einbauen :) das wären sehr viele.
Die EPs die ich für sinnvoll halte sind nun fast alle vorhanden. Es fehlen noch ein paar wenige, vielleicht habe ich auch ein paar vergessen.

**Comment by alxndr-w** [comment]
Alles klar, dann nehme ich dein Addon als Ausgangspunkt - ich brauche da für ein Projekt was ähnliches, aber umfangreicheres.

**Comment by eaCe** [comment]
Wenn ich hier etwas Hinzufügen kann das dir hilft mache ich das natürlich sehr gerne.

**Comment by eaCe** [comment]
FYI: ich habe mal eine Liste mit den EPs angelegt:
https://github.com/eaCe/activity_log#extension-points

**Comment by eaCe** [comment]
@alxndr-w wenn du vorerst keine weiteren Wünsche hast würde ich hier schlließen.
